---

- hosts: all
  remote_user: user
  vars:
    ansible_ssh_private_key_file: "{{ privkeypath }}"
    packages:
      present:
        - wireguard
        - wireguard-tools
        - htop
        - git
        - python3
        - python3-pip
        - 7zip
        - net-tools
        - dnsutils
  roles:
    - upgrade
    - install_packages
    - install_sublimetext
    - install_oh-my-zsh
    - install_spice_guest_tools
    - install_xfce
    - reboot


